### ISSUE TITLE
Examples images #5, #6 are incorrect

### ISSUE THREAD

**Issue by unlight** [rachelandrew/grid-by-example#3]
http://gridbyexample.com/examples/#example5
![Example 5](https://raw.githubusercontent.com/rachelandrew/grid-by-example/2269d7346219e0e181cfdb6eb25dee817a5e827c/examples/images/example5.png)

``` css
.b { 
    grid-column: 5 / 6; 
    grid-row: 1 / 4;
}
```

`div.b` should spans to line 4, on image it spans to 2.
Correct image:
http://imageshack.com/i/p1JOsj8Np
![](http://imagizer.imageshack.us/v2/420x233q90/901/JOsj8N.png)
Same for http://gridbyexample.com/examples/#example6

``` css
.b { 
    grid-column: 5 / 6; 
    grid-row: 1 / span 3;
}
```
